/**
 * OpenAPI Documentation Endpoint
 * Returns the OpenAPI 3.0 specification as JSON
 */

/**
 * Copyright (c) 2025 Financbase. All Rights Reserved.
 * 
 * PROPRIETARY SOFTWARE - Unauthorized copying, modification, distribution,
 * or use of this software, via any medium, is strictly prohibited.
 * 
 * @see LICENSE file in the root directory for full license terms.
 */


import { NextResponse } from 'next/server';
import swaggerJsdoc from 'swagger-jsdoc';
import { swaggerOptions } from '@/lib/openapi/config';
import { readFileSync } from 'fs';
import { join } from 'path';

export async function GET() {
	try {
		// Try to load from static file first (generated by npm run openapi:generate)
		try {
			const staticSpecPath = join(process.cwd(), 'public', 'openapi.json');
			const staticSpec = JSON.parse(readFileSync(staticSpecPath, 'utf-8'));
			
			// If static file exists and has paths, use it
			if (staticSpec && staticSpec.paths && Object.keys(staticSpec.paths).length > 0) {
				return NextResponse.json(staticSpec, {
					headers: {
						'Content-Type': 'application/json',
						'Cache-Control': 'public, max-age=3600', // Cache for 1 hour
					},
				});
			}
		} catch (staticError) {
			// Fall back to dynamic generation if static file doesn't exist
			console.log('Static OpenAPI file not found, generating dynamically...');
		}

		// Generate dynamically from source files
		const swaggerSpec = swaggerJsdoc(swaggerOptions);
		
		return NextResponse.json(swaggerSpec, {
			headers: {
				'Content-Type': 'application/json',
				'Cache-Control': 'public, max-age=3600', // Cache for 1 hour
			},
		});
	} catch (error) {
		console.error('Error generating OpenAPI spec:', error);
		return NextResponse.json(
			{
				error: 'Failed to generate API documentation',
				message: error instanceof Error ? error.message : 'Unknown error',
				hint: 'Run "npm run openapi:generate" to generate the static specification file.',
			},
			{ status: 500 }
		);
	}
}

